name: 01-ci-e2e
on: push

jobs:
  npm-test:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Git init
        run: git init

      - name: Install dependencies
        run: npm install

      - name: Connect to PostgreSQL
        run: npm run test
        env:
          API_BASE_PATH: /api
          API_SECRET: ${{ secrets.API_SECRET }}
          DB_URL: postgres://postgres:postgres@postgres:5432/postgres
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
